name: Add Issue to Personal Project

on:
  issues:
    types: [opened]

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - name: Add issue to personal project (Projects v2)
        env:
          GH_TOKEN: ${{ secrets.PROJECTS_TOKEN }}
          ISSUE_URL: ${{ github.event.issue.html_url }}
        run: |
          # Get the node ID of the issue using GitHub GraphQL API
          ISSUE_ID=$(gh api graphql -F url="$ISSUE_URL" -f query='
            query($url: URI!) {
              resource(url: $url) {
                ... on Issue {
                  id
                }
              }
            }' --jq '.data.resource.id')

          # Add the issue to your Projects v2 (Project Beta) using the correct mutation
          gh api graphql -F projectId="PROJECT_ID" -F contentId="$ISSUE_ID" -f query='
            mutation($projectId: ID!, $contentId: ID!) {
              addProjectV2Item(input: {projectId: $projectId, contentId: $contentId}) {
                item {
                  id
                }
              }
            }'
