name: Add Issue to Personal Project (Projects v2)

on:
  issues:
    types: [opened]

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get the node ID of the issue using GitHub GraphQL API
        env:
          GH_TOKEN: ${{ secrets.PROJECTS_TOKEN }}
          ISSUE_URL: ${{ github.event.issue.html_url }}
        id: get_issue_id
        run: |
          ISSUE_ID=$(gh api graphql -F url="$ISSUE_URL" -f query='
            query($url: URI!) {
              resource(url: $url) {
                ... on Issue {
                  id
                }
              }
            }' --jq '.data.resource.id')
          echo "ISSUE_ID=$ISSUE_ID" >> $GITHUB_ENV

      - name: Add the issue to your Projects v2
        env:
          GH_TOKEN: ${{ secrets.PROJECTS_TOKEN }}
        run: |
          gh api graphql -F projectId="PVT_kwHOAGSkCc4A-ChK" -F contentId="$ISSUE_ID" -f query='
            mutation($projectId: ID!, $contentId: ID!) {
              addProjectV2ItemById(input: {projectId: $projectId, contentId: $contentId}) {
                item { id }
              }
            }'
