
on:
  issues:
    types:
      - opened
      - edited
      - deleted
      - closed
      - reopened
      - labeled
      - unlabeled
      - assigned
      - unassigned
      - milestoned
      - demilestoned
      - locked
      - unlocked
      - transferred
  issue_comment:
    types:
      - created
      - edited
      - deleted

jobs:
  track:
    runs-on: ubuntu-latest
    steps:
      - name: Track issue changes
        uses: danielmeixner/issue-change-tracker@v1
